# Generated by Django 3.0.5 on 2020-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='../../static/img/somfarm.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(blank=True, default='../../static/img/farmer.png', upload_to=''),
        ),
    ]
