# Generated by Django 3.0.5 on 2020-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20200624_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, default='../../static/img/somfarm.jpg', upload_to=''),
        ),
    ]
