# Generated by Django 3.1.5 on 2021-02-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20200624_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
                ('gobolka', models.CharField(max_length=200)),
                ('product_pic', models.ImageField(blank=True, default='../../static/img/gaadhi.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.product')),
            ],
        ),
    ]
