# Generated by Django 3.1.5 on 2021-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_auto_20210206_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='total',
            field=models.IntegerField(default=200000),
            preserve_default=False,
        ),
    ]
